#!/bin/bash
LC_ALL=C
LD_LIBRARY_PATH=/opt/wheezy32/usr/lib/i386-linux-gnu
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wheezy32/usr/lib/gcc/i486-linux-gnu
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wheezy32/lib/i386-linux-gnu
LD_LINUX=/opt/wheezy32/lib/ld-linux.so.2
FIREFOX=/opt/wheezy32/usr/lib/iceweasel/iceweasel
if [ -x $FIREFOX ]; then
 $LD_LINUX $FIREFOX "$@"
else
 echo browse to $@ >&2
fi
