#!/bin/bash
LC_ALL=C
WHEEZY=/opt/wheezy32
LD_LIBRARY_PATH=$WHEEZY/usr/lib/i386-linux-gnu
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WHEEZY/usr/lib/gcc/i486-linux-gnu
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WHEEZY/lib/i386-linux-gnu
LD_LINUX=$WHEEZY/lib/ld-linux.so.2
FIREFOX=/usr/lib/iceweasel/iceweasel
if [ -x $WHEEZY/$FIREFOX ]; then
  $LD_LINUX $WHEEZY/$FIREFOX "$@"
else
  echo browse to $@ >&2
fi
