FROM wyaeld/sarge
WORKDIR /application
ENV DISPLAY=:0
ADD tmp/.X11-unix /tmp/
ADD tmp/es5-6.html /application
RUN apt-get -y install $PACKAGE
# xeyes for testing
RUN apt-get -y install xbase-clients timeout
RUN ifconfig
RUN timeout 10 xeyes
RUN timeout 10 $BROWSER /application/es5-6.html
